### ISSUE TITLE
Axelor Groovy Controller dependencies

### ISSUE THREAD

**Issue by ThatsMaddog** [axelor/axelor-development-kit#11]
I made several groovy controllers in Axelor and they work. But now i want to use an API where i can send my zipcode to and get the full address back so they don't have to fill in all the fields.
But when i use:

import org.apache.commons.httpclient.HttpClient
import org.apache.commons.httpclient.methods.GetMethod

I get this when i build or run:

unable to resolve class org.apache.commons.httpclient.HttpClient
 @ line 30, column 1.
   import org.apache.commons.httpclient.HttpClient
   ^
unable to resolve class org.apache.commons.httpclient.methods.GetMethod
 @ line 31, column 1.
   import org.apache.commons.httpclient.methods.GetMethod
   ^

i downloaded the .jar file that are necessary (http://hc.apache.org/downloads.cgi) but don't know or find where to put the jar or how to use them.

**Comment by mea-axelor** [comment]
Add as a dependency in your application's `build.gradle` script. See gradle documentation for more details.
