### ISSUE TITLE
x-bind doesn't work in an editor field

### ISSUE THREAD

**Issue by anthony-o** [axelor/axelor-development-kit#15]
Here is my use case :

```xml
            <field name="user">
                <editor>
                    <field name="code"/>
                    <field name="password"/>
                    <field name="name" x-bind="{{code}}" hidden="true"/>
                </editor>
            </field>
```

If I modify the content of the `code` field, it doesn't change the `name` field.

This code works if it's not in an `<editor>` field (testing with direct fields of the model).

I tried to use `x-bind="{{user.code}}"` with the exact same result.

**Comment by pbe-axelor** [comment]
Fixed in v3.0.4
