### ISSUE TITLE
How to show image in Grid cell?

### ISSUE THREAD

**Issue by donsunsoft** [axelor/axelor-development-kit#19]
I want to show image in grid cell, but Gird can not use Image Widget, how can i implement this function?

**Comment by mea-axelor** [comment]
You can display small image/icon using `<button>` or `<field>` like this:

```xml
<field name="imgField" x-icon="img/user.png" x-type="icon"/>
<button name="imgButton" icon="img/user.png" onClick="some.action" />
```

However, you can't set image size.

**Comment by donsunsoft** [comment]
My image url is a variable fetch from database, if x-icon can be used like this:
<field name="imgField" x-icon="#{product.imageUrl}" x-type="icon"/>

**Comment by marioestradarosa** [comment]
Can't the <viewer> </viewer> directory be applied to Grid views?
like:
<viewer><![CDATA[                
      <img src="{{product.imageUrl}}">                         
      ]]></viewer

**Comment by donsunsoft** [comment]
I tried it. `````< viewer/> ````` can not work in `````<grid/><field/> `````
