### ISSUE TITLE
Eclipse WTP support

### ISSUE THREAD

**Issue by mrp14** [axelor/axelor-development-kit#5]
Hello,

Would it be possible to add Eclipse WTP support to sdk and created applications & modules ? Or is it already supported and I missed something ?

Thanks.
Regards,

**Comment by mea-axelor** [comment]
In your application's `build.gradle` script add following:

```gradle
eclipse {
  wtp {
    component {
      resource deployPath: '/', sourcePath: 'build/webapp'
      resource deployPath: '/', sourcePath: 'src/main/webapp'
    }
  }
}
```

and re-generate eclipse projects:

```
$ ./gradlew generateCode copyWebapp cleanEclipse eclipse
```

The `copyWebapp` task will copy required webapp resources from core dependencies under `build/webapp`.

Make sure to always run this task if you clean `build` directory.
