### ISSUE TITLE
Axelor with MS SQL Server

### ISSUE THREAD

**Issue by AGELIOS** [axelor/axelor-development-kit#7]
Hi, i try to use Axelor with the jdbc for MS SQL Server 2008 with sqljdbc4.jar but i have a problem when JPA Hibernate try to find com.microsoft.sqlserver.jdbc.SQLServerDriver (not found).

Do you have instructions for me to add correctly the jar file or how to modify Classpath ?

Thank for your help.

**Comment by mea-axelor** [comment]
Yes, we don't support MS-SQL. Only PostgreSQL is officially supported and there is no plan to support other DBMS as of now.
